server:
  port: 8765

spring:
  application:
    name: GateWay
  cloud:
    gateway:
      routes:
        - id: SimpleMarket
          uri: http://localhost:8081/
          predicates:
            - Path=/market/**